### ISSUE TITLE
RFC: Vision Statement

### ISSUE THREAD

**Issue by kcranston** [carpentries/executive-council-info#2]
# RFC for Vision Statement

With the vision statement, we are asking: "what is the future we are trying to achieve?". A vision statement should be short, inspiring, and not change often. Here is the draft vision statement for the Carpentries:

> A diverse, inclusive community for teaching and learning data & computing skills

Background:

The goal of this statement was to center the Carpentry's community, emphasize
the group's commitment to diversity and inclusion, make clear that the
organization is focused on building community around teaching as well as on
delivering material, and avoid using "and" three times in a single sentence.

**Comment by remram44** [comment]
Maybe it should be more focused on what we want to accomplish, rather than how, if we are calling it our "vision"? E.g. we want more researchers to have computing skills, rather than create a community that teaches computing skills? (if that is the case)

**Comment by jezcope** [comment]
> avoid using "and" three times in a single sentence
:rofl: :+1:

**Comment by hoytpr** [comment]
I like the statement, but to be more inspirational, how about 

**The best** diverse, inclusive community for teaching and learning data & computing skills.

**Comment by kariljordan** [comment]
+1 to adding an adjective in front of the word diverse!

**Comment by gvwilson** [comment]
"computational skills" instead of "data & computing skills" ?  I'm not sure what a "data skill" is...

**Comment by JasonJWilliamsNY** [comment]
There is no mention that the focus that our community is largely aimed at researchers. Also, I think a vision statement needs a verb, are we creating something, being something, changing something? 

"To be the largest and most welcoming community of researchers who teach and share computational skills"

Maybe a *little* closer?

**Comment by remram44** [comment]
I think we need @kcranston to specify whether this vision is the committee's vision, e.g. "create a community of teachers", or whether it's the organization's as a whole (including us teachers), e.g. "teach".

Right now it looks like the former, i.e. it's not *my* vision but the administration staff/committee's. Is that the case?

If it should be the latter, then the vision should be "teaching people skills" rather than "create a community of teachers".

**Comment by kcranston** [comment]
Thanks, all for your comments so far. To answer @remram44 specific question, we are drafting a vision statement for the organization, certainly not just for the executive council or the staff.

There are a couple of interesting threads here:

* whether our focus is on teaching learners vs building communities around teaching 
* making the vision statement more about the world we want to see rather than what we do

A few years ago, I would have definitely said that teaching is our primary focus, but now I think our community building is potentially the bigger impact (based on our activities, results from surveys, etc).

**Comment by JasonJWilliamsNY** [comment]
@kcranston Agreed! The community aspect is tremendous. Carpentries has a global community that does not exist for anything else I can think of in the sciences. Teaching and learning are side-by-side with that, but community building is what makes the teaching and learning sustainable.

**Comment by hoytpr** [comment]
Building communities through teaching and learning.

**Comment by jezcope** [comment]
@kcranston I think one of the things that's always drawn me to the Carpentries is the emphasis on giving people the skills to teach well and building a community of practice around that, so not just a community of teachers but one with an explicit aim to make better teachers.

@JasonJWilliamsNY I agree that the primary focus is researchers themselves but let's not forget the rest of our community, especially the librarians, technicians and IT staff. How about "researchers and those who support them"?

**Comment by JasonJWilliamsNY** [comment]
@jezcope I consider all of the folks you mentioned "researchers" - but maybe there is a better term. I avoided the term scientist.

**Comment by JasonJWilliamsNY** [comment]
I agree with @hoytpr sentiments, but as a statement, I would want to know that it was a community of... (researchers?). We don't target people in general, but folks working in some kind of science and research. I think that focus is a differentiator. Of course we are inclusive, so that means we are open to folks going down that track. Perhaps (one day?) we will have an even broader audience, but not clear (to me) we are going for that now.

**Comment by ha0ye** [comment]
I lean towards *not* including "researchers". I think the general skills around programming and data analysis are broadly applicable, and it would distinguish The Carpentries a bit from e.g. the more specific groups targeted by Library Carpentry and Author Carpentry.

**Comment by hoytpr** [comment]
Building communities that embolden sciences through teaching and learning.

**Comment by ethanwhite** [comment]
> "computational skills" instead of "data & computing skills" ? I'm not sure what a "data skill" is...

We discussed and worked on this language a lot in the initial drafting because the language can definitely feel awkward in places. However, we felt that including "data" in the description was important since a large number of novices identify strongly with "data" relative to "computing". "Data skills" is now in wide use with ~300,000 pages returned by Google.

**Comment by remram44** [comment]
Hello again!

I see a lot of great new suggestions here, but they don't look like "visions" at all (i.e. what we want to *see*), maybe we should rename the whole endeavor to "mission statement" (i.e. what we want to *do*).

That would allow us to focus it more on the "being a community that changes the world", rather than "the world we want to see".

**Comment by ethanwhite** [comment]
@remram44 there is a separate mission statement under discussion in #1.

**Comment by pitviper6** [comment]
**Specific roles**
I'd not use 'researchers' - librarians are mostly NOT researchers, but do use, transform and clean data constantly in all kinds of contexts (harmonizing metadata, and creating complex financial/demographic reports from a wide array of sources). They are getting heavily into data viz as well.
**Author Carpentry**
This isn't associated with The Carpentries, I think?
**Motivations**
 A big part of why I got so involved in the Carpentries is for the community centering around instruction and lesson development. I'd never done these things before and found out I loved it and wanted to gain expertise. 
**The word 'data'**
It is important to keep the word data in there. Many of our lessons are about analyzing, normalizing and learning matching/text mining skills. These aren't really computational (well, the last one is, kind of).

My attempt at a vision statement:
To build the best community for learning data and computational skills through inclusive, diverse teaching methods and mindful lesson development <--I only used TWO 'and's!

**Comment by quirksahern** [comment]
I like it

Sent from my iPhone

On 21 Aug 2018, at 20:43, Juliane Schneider <notifications@github.com<mailto:notifications@github.com>> wrote:


Specific roles
I'd not use 'researchers' - librarians are mostly NOT researchers, but do use, transform and clean data constantly in all kinds of contexts (harmonizing metadata, and creating complex financial/demographic reports from a wide array of sources). They are getting heavily into data viz as well.
Author Carpentry
This isn't associated with The Carpentries, I think?
Motivations
A big part of why I got so involved in the Carpentries is for the community centering around instruction and lesson development. I'd never done these things before and found out I loved it and wanted to gain expertise.
The word 'data'
It is important to keep the word data in there. Many of our lessons are about analyzing, normalizing and learning matching/text mining skills. These aren't really computational (well, the last one is, kind of).

My attempt at a vision statement:
To build the best community for learning data and computational skills through inclusive, diverse teaching methods and mindful lesson development <--I only used TWO 'and's!

**Comment by hlapp** [comment]
I like the statement, but one property that's I think important for a vision statement that continues to guide how to drive action in the desired direction is that it's clearly distinguishable from the status quo. In other words, a vision statement shouldn't be geared towards maintenance.

At least to me, it's not immediately clear how the Carpentries in major and important ways _aren't_ already _A diverse, inclusive community for teaching and learning data & computing skills_.

**Comment by brownsarahm** [comment]
re: @kariljordan's first comment about this being about  where we're going and keep this different from the mission (since both will exist, they should probably? be compatible but not fully redundant)

Maybe something like this:
_To build a diverse, inclusive community of practice around data management & computational skills for  research and scholarship._

This would include the day that the novice workshops we currently do aren't needed because a community of practice includes best practice sharing and continual learning.  

I think this still includes librarians, though not explicitly, bc librarians are definitely a part of the community that supports research. As noted in the mission discussion, I think some mention of research is important because otherwise maybe it includes k-12 education or personal data literacy

**Comment by quirksahern** [comment]
I like the research and scholarship

Sent from my iPhone

On 26 Sep 2018, at 21:47, Sarah Brown <notifications@github.com<mailto:notifications@github.com>> wrote:


re: @kariljordan<https://github.com/kariljordan>'s first comment about this being about where we're going and keep this different from the mission (since both will exist, they should probably? be compatible but not fully redundant)

Maybe something like this:
To build a diverse, inclusive community of practice around data management & computational skills for research and scholarship.

This would include the day that the novice workshops we currently do aren't needed because a community of practice includes best practice sharing and continual learning.

I think this still includes librarians, though not explicitly, bc librarians are definitely a part of the community that supports research. As noted in the mission discussion, I think some mention of research is important because otherwise maybe it includes k-12 education or personal data literacy

**Comment by ha0ye** [comment]
I wonder if a subtle wording change from "community" to "communities" is worthwhile? In my mind, "community" has a more of a local-ish feel, compared to the global reach of the Carpentries.

Perhaps this is just my bias towards decentralized networks of communities as feeling more diverse and inclusive than something branded as "**a** community".

**Comment by brownsarahm** [comment]
@ha0ye i like that... maybe:

_To build a global network of diverse, inclusive communities of practice around data management & computational skills for research and scholarship._

**Comment by tracykteal** [comment]
Thank you for all the feedback and discussion around the vision! One of the main sets of feedback is that the vision should be aspirational and guide where we're going rather than just reflect where we are. With that perspective the Executive Council brought together the feedback and created the Vision statement: The Carpentries vision is to be "the leading inclusive community teaching data and coding skills". 

More in the blog post about how creating this aspiration means that it guides us forward and that there is always more that we can and should do. https://carpentries.org/blog/2019/11/carpentries-vision/ 

Thank you not only to the conversation here and the work everyone is doing in the community, but to all who contributed to these efforts in big, small, visible and less visible ways, and the opportunity to work together towards this vision.

**Comment by amyehodge** [comment]
Vision has been completed. See https://carpentries.org/blog/2019/11/carpentries-vision/
