### ISSUE TITLE
Activist Council

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries/executive-council-info#23]
The https://github.com/carpentries/executive-council-info/blob/master/process/roles_responsibilities.md currently states (emphasis added)

> The Carpentries Executive Council (EC) is an activist Council, which means that Council members are expected to volunteer their time to participate actively in the Carpentries community _in addition to their duties as EC members_, and to be dedicated to the Carpentries organization as a whole. 

To me this looks like it formalises active membership in the community (being an active instructor, trainer, mentor, maintainer, ...) as part of being on the EC. This could pose a problem for those interested in joining the EC as council-elected members from _outside_ the organisation.

Am I misintrepreting/overintrepreting the phrasing, or should we adjust it?

**Comment by amyehodge** [comment]
@lexnederbragt I don't think you're misinterpreting/overinterpreting. I think we are so used to everyone being involved that we hadn't really considered how this would impact people we get on the EC for the expertise we need but who aren't active community members. 

Is it appropriate to apply this to community-elected members and not EC-elected members?

**Comment by k8hertweck** [comment]
I think this is a valid concern @lexnederbragt has raised. I not personally in favor of differentiating responsibilities between community and council elected members, but am amenable to reframing the language so that it clarifies what this means. In my mind, this means that EC members are expected to engage in the general events of the community, which includes things like reading the newsletter and attending community calls when applicable. 

I've removed that sentence from the page linked above, which allows the language to reflect that present on the [main website](http://static.carpentries.org/governance/).

**Comment by k8hertweck** [comment]
Closing this, as it appears to have been adequately resolved.
