### ISSUE TITLE
Renaming this repository

### ISSUE THREAD

**Issue by kariljordan** [carpentries/executive-council-info#91]
To prepare for the upcoming governance transition I am interested in renaming this repository from **executive-council-info** to **governance** to keep all of the Executive Council minutes and the Board of Directors minutes in the same repository. This repo is linked to/from many places, so I want to check with @maneesha about the best way to accomplish this.

**Comment by maneesha** [comment]
For the sake of consistency, we can update links in other places.  However, when we rename the repo, all links to the previous name will automatically re-redirect. So it is ok if we miss something.  Additionally since we have no external automations on this repo, there should be no impact in renaming this repo.  

Closing this issue here.
